module.exports = [
  {
    // Plan & Create
    promoterName: 'JOHN CARRINGTON',
    USRN: '08400189',
    roadCategoryGroup: '1',
    highwayAuthority: 'Highway Authority',
    workReferenceNumber: 'CT0224443466',
    startDay: '28',
    startMonth: '03',
    startYear: '2017',
    endDay: '30',
    endMonth: '03',
    endYear: '2017',
    duration: '2 Days',
    trafficManagementTypeGroup: 'Stop/go boards',
    workCategoryGroup: 'Minor',
    screen1Complete: true,
    // Location & contact
    worksLocationDescription: 'Location 1234',
    worksLocationGroup: [ 'Footway', 'Cycleway' ],
    descriptionOfWorkGroup: 'Leakage',
    descriptionOfWork2: '',
    excavationGroup: 'Yes',
    contactDetails: 'Brian Smith - 077389477298',
    promoterAgent: '',
    secondaryContact: '',
    commerciallySensitiveGroup: 'No',
    laneRentalGroup: 'No',
    screen2Complete: true,
    // Conditions
    conditionsName: ['NCT01a'],
    conditionsReason: ['Standard Condition'],
    screen3Complete: true,
    // Collaboration
    tmGroup: 'Yes',
    fileAttachedDetail: ['TM Plan'],
    fileAttachedName: ['c17-2006.png'],
    collaborationGroup: 'No',
    collaborationTypeGroup: '',
    collaborationDetails: '',
    environmentalHealthGroup: 'No',
    projectReference: 'ABC12345',
    screen4Complete: true
  },

  {
    // Plan & Create
    promoterName: '',
    USRN: '',
    roadCategoryGroup: '',
    highwayAuthority: '',
    workReferenceNumber: '',
    startDay: '',
    startMonth: '',
    startYear: '',
    endDay: '',
    endMonth: '',
    endYear: '',
    duration: '',
    trafficManagementTypeGroup: '',
    workCategoryGroup: '',
    screen1Complete: false,
    // Location & contact
    worksLocationDescription: '',
    worksLocationGroup: [ '' ],
    descriptionOfWorkGroup: '',
    descriptionOfWork2: '',
    excavationGroup: '',
    contactDetails: '',
    promoterAgent: '',
    secondaryContact: '',
    commerciallySensitiveGroup: '',
    laneRentalGroup: '',
    screen2Complete: false,
    // Conditions
    conditionsName: [''],
    conditionsReason: [''],
    screen3Complete: false,
    // Collaboration
    tmGroup: '',
    fileAttachedDetail: [''],
    fileAttachedName: [''],
    collaborationGroup: '',
    collaborationTypeGroup: '',
    collaborationDetails: '',
    environmentalHealthGroup: '',
    projectReference: '',
    screen4Complete: false
  },

  {
    // Plan & Create
    promoterName: '',
    USRN: '',
    roadCategoryGroup: '',
    highwayAuthority: '',
    workReferenceNumber: '',
    startDay: '',
    startMonth: '',
    startYear: '',
    endDay: '',
    endMonth: '',
    endYear: '',
    duration: '',
    trafficManagementTypeGroup: '',
    workCategoryGroup: '',
    screen1Complete: false,
    // Location & contact
    worksLocationDescription: '',
    worksLocationGroup: [ '' ],
    descriptionOfWorkGroup: '',
    descriptionOfWork2: '',
    excavationGroup: '',
    contactDetails: '',
    promoterAgent: '',
    secondaryContact: '',
    commerciallySensitiveGroup: '',
    laneRentalGroup: '',
    screen2Complete: false,
    // Conditions
    conditionsName: [''],
    conditionsReason: [''],
    screen3Complete: false,
    // Collaboration
    tmGroup: '',
    fileAttachedDetail: [''],
    fileAttachedName: [''],
    collaborationGroup: '',
    collaborationTypeGroup: '',
    collaborationDetails: '',
    environmentalHealthGroup: '',
    projectReference: '',
    screen4Complete: false
  }
]
