module.exports = [
  {
    promoterName: 'JOHN CARRINGTON',
    USRN: '08400189',
    roadCategoryGroup: '',
    highwayAuthority: 'Highway Authority',
    workReferenceNumber: '4',
    startDay: '28',
    startMonth: '30',
    startYear: '2017',
    endDay: '30',
    endMonth: '03',
    endYear: '2017',
    duration: '2 Days',
    trafficManagementTypeGroup: '',
    workCategoryGroup: '',
    worksLocationDescription: '',
    worksLocationGroup: '',
    descriptionOfWorkGroup: '',
    descriptionOfWork2: '',
    excavationGroup: '',
    contactDetails: '',
    promoterAgent: '',
    secondaryContact: '',
    commerciallySensitiveGroup: '',
    laneRentalGroup: '',
    tmGroup: '',
    fileAttachedDetail: [],
    fileAttachedName: [],
    collaborationGroup: '',
    collaborationTypeGroup: '',
    collaborationDetails: 'dfh',
    environmentalHealthGroup: '',
    projectReference: '',
    conditionsName: ''
  },

  {
    promoterName: '',
    USRN: '',
    roadCategoryGroup: '',
    highwayAuthority: '',
    workReferenceNumber: '',
    startDay: '',
    startMonth: '',
    startYear: '',
    endDay: '',
    endMonth: '',
    endYear: '',
    duration: '',
    trafficManagementTypeGroup: '',
    workCategoryGroup: '',
    worksLocationDescription: '',
    worksLocationGroup: '',
    descriptionOfWorkGroup: '',
    descriptionOfWork2: '',
    excavationGroup: '',
    contactDetails: '',
    promoterAgent: '',
    secondaryContact: '',
    commerciallySensitiveGroup: '',
    laneRentalGroup: '',
    tmGroup: '',
    fileAttachedDetail: [],
    fileAttachedName: [],
    collaborationGroup: '',
    collaborationTypeGroup: '',
    collaborationDetails: '',
    environmentalHealthGroup: '',
    projectReference: '',
    conditionsName: ''
  },

  {
    promoterName: '',
    USRN: '',
    roadCategoryGroup: '',
    highwayAuthority: '',
    workReferenceNumber: '',
    startDay: '',
    startMonth: '',
    startYear: '',
    endDay: '',
    endMonth: '',
    endYear: '',
    duration: '',
    trafficManagementTypeGroup: '',
    workCategoryGroup: '',
    worksLocationDescription: '',
    worksLocationGroup: '',
    descriptionOfWorkGroup: '',
    descriptionOfWork2: '',
    excavationGroup: '',
    contactDetails: '',
    promoterAgent: '',
    secondaryContact: '',
    commerciallySensitiveGroup: '',
    laneRentalGroup: '',
    tmGroup: '',
    fileAttachedDetail: [],
    fileAttachedName: [],
    collaborationGroup: '',
    collaborationTypeGroup: '',
    collaborationDetails: '',
    environmentalHealthGroup: '',
    projectReference: '',
    conditionsName: ''
  }

]
